### This is a personal project to predict that a women is having breast cancer or not

### In this we will Train a basic neural network

In [1]:
import numpy as np 
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_breast_cancer

In [2]:
df = pd.read_csv(
    'https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv'
)
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns= ['id','Unnamed: 32'], inplace = True)

In [5]:
df.head(
)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
df.shape

(569, 31)

### Train - Test - Split

In [7]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

### Scaling

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[ 1.56817263,  0.11933708,  1.57486993, ...,  2.10736425,
        -0.21762259,  2.67168483],
       [-0.82046758,  3.40964848, -0.86653578, ..., -1.28718973,
         0.05799056, -0.60220617],
       [-0.55100875, -1.23065488, -0.60328288, ..., -1.46408556,
        -0.99342257, -1.33641799],
       ...,
       [ 0.824354  ,  1.84328151,  0.78022111, ...,  0.64297446,
         0.22642082,  0.4112374 ],
       [-0.14962738,  1.26471353, -0.17498754, ...,  0.2953357 ,
         1.00902607, -0.25938128],
       [-0.2983911 , -0.84729479, -0.26178764, ..., -0.6286758 ,
         0.52244976, -0.09577344]], shape=(455, 30))

In [9]:
y_train   # The values are in string format . we need to convert them into numerical format using label encoder for the neural network to understand it .

252    M
232    B
316    B
455    B
431    B
      ..
344    B
300    M
460    M
126    M
20     B
Name: diagnosis, Length: 455, dtype: str

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train= encoder.fit_transform(df.iloc[:,0])
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0])

### Numpy arrays to Pytorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[ 1.5682,  0.1193,  1.5749,  ...,  2.1074, -0.2176,  2.6717],
        [-0.8205,  3.4096, -0.8665,  ..., -1.2872,  0.0580, -0.6022],
        [-0.5510, -1.2307, -0.6033,  ..., -1.4641, -0.9934, -1.3364],
        ...,
        [ 0.8244,  1.8433,  0.7802,  ...,  0.6430,  0.2264,  0.4112],
        [-0.1496,  1.2647, -0.1750,  ...,  0.2953,  1.0090, -0.2594],
        [-0.2984, -0.8473, -0.2618,  ..., -0.6287,  0.5224, -0.0958]],
       dtype=torch.float64)

In [14]:
y_train_tensor.shape

torch.Size([569])

## Defining the Model

In [15]:
class MysimpleNN():
    def __init__(self,input_size):
        self.weights = torch.rand(input_size,1,dtype= torch.float64,requires_grad = True)
        self.bias = torch.zeros(1,dtype= torch.float64,requires_grad = True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Important Parameters

In [16]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [17]:
# Create  Model
model = MysimpleNN(input_size = X_train_tensor.shape[1])
model.weights
# define loop
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(X_train_tensor)
    

    # loss calculation
    loss = model.loss_function(y_pred,y_train_tensor)

    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():

        model.weights.data -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 3.9792009384092872
Epoch 2, Loss: 3.8662824684879515
Epoch 3, Loss: 3.750388128106228
Epoch 4, Loss: 3.629908359685931
Epoch 5, Loss: 3.505246280192032
Epoch 6, Loss: 3.373970536816626
Epoch 7, Loss: 3.236624775653392
Epoch 8, Loss: 3.098056914555486
Epoch 9, Loss: 2.958257660258108
Epoch 10, Loss: 2.820265379151045
Epoch 11, Loss: 2.6776248498597863
Epoch 12, Loss: 2.5339104972283173
Epoch 13, Loss: 2.390847866495797
Epoch 14, Loss: 2.249982661539912
Epoch 15, Loss: 2.1153774478699408
Epoch 16, Loss: 1.985783808991663
Epoch 17, Loss: 1.8564063040060605
Epoch 18, Loss: 1.7326931974087352
Epoch 19, Loss: 1.6168072179070558
Epoch 20, Loss: 1.5090632075523172
Epoch 21, Loss: 1.4122053957691343
Epoch 22, Loss: 1.3229483739797496
Epoch 23, Loss: 1.2434294753840105
Epoch 24, Loss: 1.1750502422067426
Epoch 25, Loss: 1.1145320235348735

In [18]:
model.bias

tensor([-0.0866], dtype=torch.float64, requires_grad=True)

### Model Evaluation

In [19]:
# evaluate the model on test data
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred_labels = (y_pred > 0.9).float()
    accuracy = (y_pred_labels.squeeze() == y_test_tensor).float().mean()
print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.5877193212509155

### Building an Neural Network with Torch.nn Modeule

In [20]:
import torch.nn as nn

In [ ]:
#  Create Model class using nn.Module

class model(nn.Module):

    def __init__(self,num_features):         # constructor to initialize the layers of the model and num_features is the number of features in the dataset .
        super().__init__()                   # invoke the constructor of the parent class nn.Module
        self.linear = nn.Linear(num_features,1)  # Linear layer takes all the features and produces a single output for binary classification
        self.sigmoid = nn.Sigmoid()             # Sigmoid activation function to convert the output of the linear layer into a probability between 0 and 1
    
    def forward(self,features):
        out = self.linear(features)              # pass the input feature through the linear layer to get the raw output (logits)
        out = self.sigmoid(out)                 # pass the logits through the sigmoid activation function to get the predicted probabilities
        return out

In [22]:
# create dataset
features = torch.rand(10,5)
# Create Model
model = model(features.shape[1])
# call model for forward pass
model(features)

tensor([[0.5260],
        [0.5037],
        [0.4246],
        [0.4580],
        [0.4298],
        [0.5038],
        [0.5311],
        [0.4557],
        [0.4679],
        [0.5651]], grad_fn=<SigmoidBackward0>)

In [23]:
# Show Model Weights 
model.linear.weight

Parameter containing:
tensor([[ 0.1533, -0.2605,  0.0600, -0.2884, -0.4064]], requires_grad=True)

In [24]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.2371], requires_grad=True)

In [25]:
from torchinfo import summary
summary(model,input_size = (10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================