### This is a personal project to predict that a women is having breast cancer or not

### In this we will Train a basic neural network

In [101]:
import numpy as np 
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [102]:
df = pd.read_csv(
    'https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv'
)
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [103]:
df.shape

(569, 33)

In [104]:
df.drop(columns= ['id','Unnamed: 32'], inplace = True)

In [105]:
df.head(
)

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [106]:
df.shape

(569, 31)

### Train - Test - Split

In [107]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

### Scaling

In [108]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.11301125, -0.72996577, -0.18105568, ..., -0.94840425,
        -0.85660326, -0.71365185],
       [ 1.11713509,  0.13946589,  1.08508057, ...,  1.16732727,
         0.2712079 , -0.01163139],
       [ 0.28861187,  1.35943763,  0.38438741, ...,  1.30874496,
         1.82214936,  0.83191192],
       ...,
       [ 0.85032253, -0.52932769,  0.81620994, ...,  1.05204112,
         0.39187244, -0.154273  ],
       [ 1.31092526,  0.44618846,  1.24803247, ...,  0.947515  ,
        -0.55252864, -1.00676637],
       [-0.23097048, -0.24797315, -0.25927259, ..., -0.58640572,
        -0.34820337, -0.99893507]])

In [109]:
y_train   # The values are in string format . we need to convert them into numerical format using label encoder for the neural network to understand it .

357    B
6      M
28     M
461    M
32     M
      ..
297    M
309    B
253    M
70     M
93     B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [110]:
encoder = LabelEncoder()
y_train= encoder.fit_transform(df.iloc[:,0])
y_test = encoder.transform(y_test)

In [111]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0])

### Numpy arrays to Pytorch tensors

In [112]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [113]:
X_train_tensor

tensor([[-0.1130, -0.7300, -0.1811,  ..., -0.9484, -0.8566, -0.7137],
        [ 1.1171,  0.1395,  1.0851,  ...,  1.1673,  0.2712, -0.0116],
        [ 0.2886,  1.3594,  0.3844,  ...,  1.3087,  1.8221,  0.8319],
        ...,
        [ 0.8503, -0.5293,  0.8162,  ...,  1.0520,  0.3919, -0.1543],
        [ 1.3109,  0.4462,  1.2480,  ...,  0.9475, -0.5525, -1.0068],
        [-0.2310, -0.2480, -0.2593,  ..., -0.5864, -0.3482, -0.9989]],
       dtype=torch.float64)

In [114]:
y_train_tensor.shape

torch.Size([569])

## Defining the Model

In [122]:
class MysimpleNN():
    def __init__(self,input_size):
        self.weights = torch.rand(input_size,1,dtype= torch.float64,requires_grad = True)
        self.bias = torch.zeros(1,dtype= torch.float64,requires_grad = True)

### Important Parameters

In [123]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [125]:
# Create  Model
model = MysimpleNN(X_train_tensor)
model.weights

TypeError: rand() received an invalid combination of arguments - got (Tensor, int, requires_grad=bool, dtype=torch.dtype), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, torch.Generator generator, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)