### This is a personal project to predict that a women is having breast cancer or not

### In this we will Train a basic neural network

In [1]:
import numpy as np 
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.datasets import load_breast_cancer

In [2]:
df = pd.read_csv(
    'https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv'
)
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns= ['id','Unnamed: 32'], inplace = True)

In [5]:
df.head(
)

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [6]:
df.shape

(569, 31)

### Train - Test - Split

In [7]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

### Scaling

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[ 0.72053466,  0.51894842,  0.74709813, ...,  1.43694741,
         1.1066167 ,  0.62293462],
       [-1.02339259,  0.92171336, -1.03125728, ..., -1.22671788,
        -1.08091975, -0.88803334],
       [-0.55474765, -0.27009399, -0.55977673, ..., -0.84341906,
        -0.79840242, -0.37190794],
       ...,
       [-1.33724269,  0.59431964, -1.33005396, ..., -1.13033279,
        -0.06291036, -0.06017253],
       [ 0.24904944,  1.41869231,  0.1511533 , ..., -1.26049001,
        -2.12576039, -1.57818843],
       [-0.37865076, -0.63281797, -0.43283965, ..., -0.81472768,
        -0.83470353, -1.08700185]])

In [9]:
y_train   # The values are in string format . we need to convert them into numerical format using label encoder for the neural network to understand it .

24     M
299    B
480    B
208    B
111    B
      ..
35     M
248    B
416    B
38     M
69     B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [10]:
encoder = LabelEncoder()
y_train= encoder.fit_transform(df.iloc[:,0])
y_test = encoder.transform(y_test)

In [11]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0])

### Numpy arrays to Pytorch tensors

In [12]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [13]:
X_train_tensor

tensor([[ 0.7205,  0.5189,  0.7471,  ...,  1.4369,  1.1066,  0.6229],
        [-1.0234,  0.9217, -1.0313,  ..., -1.2267, -1.0809, -0.8880],
        [-0.5547, -0.2701, -0.5598,  ..., -0.8434, -0.7984, -0.3719],
        ...,
        [-1.3372,  0.5943, -1.3301,  ..., -1.1303, -0.0629, -0.0602],
        [ 0.2490,  1.4187,  0.1512,  ..., -1.2605, -2.1258, -1.5782],
        [-0.3787, -0.6328, -0.4328,  ..., -0.8147, -0.8347, -1.0870]],
       dtype=torch.float64)

In [14]:
y_train_tensor.shape

torch.Size([569])

## Defining the Model

In [15]:
class MysimpleNN():
    def __init__(self,input_size):
        self.weights = torch.rand(input_size,1,dtype= torch.float64,requires_grad = True)
        self.bias = torch.zeros(1,dtype= torch.float64,requires_grad = True)

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred

    def loss_function(self,y_pred,y):
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

### Important Parameters

In [16]:
learning_rate = 0.1
epochs = 25

### Training Pipeline

In [17]:
# Create  Model
model = MysimpleNN(input_size = X_train_tensor.shape[1])
model.weights
# define loop
for epoch in range(epochs):
    # Forward pass
    y_pred = model.forward(X_train_tensor)
    

    # loss calculation
    loss = model.loss_function(y_pred,y_train_tensor)

    # backward pass
    loss.backward()

    # parameter update
    with torch.no_grad():

        model.weights.data -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

Epoch 1, Loss: 3.7824853541219343
Epoch 2, Loss: 3.657893871070697
Epoch 3, Loss: 3.52257641550975
Epoch 4, Loss: 3.3832299867005764
Epoch 5, Loss: 3.2405583481657447
Epoch 6, Loss: 3.0941502341954146
Epoch 7, Loss: 2.945596285466426
Epoch 8, Loss: 2.7920414094355843
Epoch 9, Loss: 2.6351315131582296
Epoch 10, Loss: 2.4787421306009194
Epoch 11, Loss: 2.327745725295729
Epoch 12, Loss: 2.1773505614191273
Epoch 13, Loss: 2.0271738892284943
Epoch 14, Loss: 1.8866507831240396
Epoch 15, Loss: 1.7551039868543237
Epoch 16, Loss: 1.628665245783693
Epoch 17, Loss: 1.5110672537397212
Epoch 18, Loss: 1.4053277515707816
Epoch 19, Loss: 1.3116059637446766
Epoch 20, Loss: 1.2297338226610277
Epoch 21, Loss: 1.1591575843945177
Epoch 22, Loss: 1.0989613711310042
Epoch 23, Loss: 1.047965024429281
Epoch 24, Loss: 1.0048707324808444
Epoch 25, Loss: 0.9684073696974111

In [18]:
model.bias

tensor([-0.1539], dtype=torch.float64, requires_grad=True)

### Model Evaluation

In [19]:
# evaluate the model on test data
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred_labels = (y_pred > 0.9).float()
    accuracy = (y_pred_labels.squeeze() == y_test_tensor).float().mean()
print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.6578947305679321

### Building an Neural Network with Torch.nn Modeule

In [28]:
import torch.nn as nn

In [ ]:
#  Create Model class using nn.Module

class model(nn.Module):

    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out